/* Generated By:JJTree: Do not edit this line. ASTcompoundStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcompoundStmt extends SimpleNode {
  public ASTcompoundStmt(int id) {
    super(id);
  }

  public ASTcompoundStmt(MyCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9faf9c7110d80e3e7e4971e3ed519ace (do not edit this line) */
