/* Generated By:JJTree: Do not edit this line. ASTexpressionStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTexpressionStmt extends SimpleNode {
  public ASTexpressionStmt(int id) {
    super(id);
  }

  public ASTexpressionStmt(MyCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea69e11c1a909690710f38001850fe22 (do not edit this line) */
