/* Generated By:JJTree: Do not edit this line. ASTiterationStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTiterationStmt extends SimpleNode {
  public ASTiterationStmt(int id) {
    super(id);
  }

  public ASTiterationStmt(MyCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9067226c335129dd2bdf5473b34ee0bc (do not edit this line) */
