/* Generated By:JJTree: Do not edit this line. ASTmatchedStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmatchedStmt extends SimpleNode {
  public ASTmatchedStmt(int id) {
    super(id);
  }

  public ASTmatchedStmt(MyCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0eeb3ef4c646a7ff48e108e7656f9dcc (do not edit this line) */
