/* Generated By:JJTree: Do not edit this line. ASTsimpleExperession.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsimpleExperession extends SimpleNode {
  public ASTsimpleExperession(int id) {
    super(id);
  }

  public ASTsimpleExperession(MyCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0d7ff2ff230325ecc96ed4af9252ca40 (do not edit this line) */
