/* Generated By:JJTree: Do not edit this line. ASTtypeSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtypeSpecifier extends SimpleNode {
  public ASTtypeSpecifier(int id) {
    super(id);
  }

  public ASTtypeSpecifier(MyCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dca2bc5f1b47acb34ea4ae3be957cb3c (do not edit this line) */
