/* Generated By:JavaCC: Do not edit this line. MyCompilerVisitor.java Version 5.0 */
public interface MyCompilerVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTdeclarationList node, Object data);
  public Object visit(ASTdeclaration node, Object data);
  public Object visit(ASTvarDeclaration node, Object data);
  public Object visit(ASTfunDeclaration node, Object data);
  public Object visit(ASTparams node, Object data);
  public Object visit(ASTparamList node, Object data);
  public Object visit(ASTparam node, Object data);
  public Object visit(ASTcompoundStmt node, Object data);
  public Object visit(ASTlocalDeclarations node, Object data);
  public Object visit(ASTstatementList node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTexpressionStmt node, Object data);
  public Object visit(ASTselectionStmt node, Object data);
  public Object visit(ASTiterationStmt node, Object data);
  public Object visit(ASTreturnStmt node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTvar node, Object data);
  public Object visit(ASTsimpleExperession node, Object data);
  public Object visit(ASTrelop node, Object data);
  public Object visit(ASTadditiveExpression node, Object data);
  public Object visit(ASTterm node, Object data);
  public Object visit(ASTaddop node, Object data);
  public Object visit(ASTmulop node, Object data);
  public Object visit(ASTfactor node, Object data);
  public Object visit(ASTcall node, Object data);
  public Object visit(ASTargs node, Object data);
  public Object visit(ASTargList node, Object data);
}
/* JavaCC - OriginalChecksum=2d695668086d29c1291f1c0b6ac054a0 (do not edit this line) */
