/* Generated By:JJTree&JavaCC: Do not edit this line. MyCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int OUTPUT = 13;
  /** RegularExpression Id. */
  int INPUT = 14;
  /** RegularExpression Id. */
  int letter = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int digit = 17;
  /** RegularExpression Id. */
  int NUM = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int NOTEQUAL = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int TIMES = 25;
  /** RegularExpression Id. */
  int DIVIDE = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int LEFTPARENTHESES = 28;
  /** RegularExpression Id. */
  int RIGHTPARENTHESES = 29;
  /** RegularExpression Id. */
  int LEFTBRACKET = 30;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 31;
  /** RegularExpression Id. */
  int ALLBRACKET = 32;
  /** RegularExpression Id. */
  int ARRAYELEMENT = 33;
  /** RegularExpression Id. */
  int LEFTBRACES = 34;
  /** RegularExpression Id. */
  int RIGHTBRACES = 35;
  /** RegularExpression Id. */
  int LT = 36;
  /** RegularExpression Id. */
  int GT = 37;
  /** RegularExpression Id. */
  int LTE = 38;
  /** RegularExpression Id. */
  int GTE = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"int\"",
    "\"return\"",
    "\"void\"",
    "\"output\"",
    "\"input\"",
    "<letter>",
    "<ID>",
    "<digit>",
    "<NUM>",
    "\";\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<ALLBRACKET>",
    "<ARRAYELEMENT>",
    "\"{\"",
    "\"}\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
  };

}
