/* Generated By:JavaCC: Do not edit this line. MyCompilerTreeConstants.java Version 5.0 */
public interface MyCompilerTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATIONLIST = 1;
  public int JJTDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTFUNDECLARATION = 4;
  public int JJTPARAMS = 5;
  public int JJTPARAMLIST = 6;
  public int JJTPARAM = 7;
  public int JJTCOMPOUNDSTMT = 8;
  public int JJTLOCALDECLARATIONS = 9;
  public int JJTSTATEMENTLIST = 10;
  public int JJTSTATEMENT = 11;
  public int JJTEXPRESSIONSTMT = 12;
  public int JJTSELECTIONSTMT = 13;
  public int JJTITERATIONSTMT = 14;
  public int JJTRETURNSTMT = 15;
  public int JJTEXPRESSION = 16;
  public int JJTVAR = 17;
  public int JJTSIMPLEEXPERESSION = 18;
  public int JJTRELOP = 19;
  public int JJTADDITIVEEXPRESSION = 20;
  public int JJTTERM = 21;
  public int JJTADDOP = 22;
  public int JJTMULOP = 23;
  public int JJTFACTOR = 24;
  public int JJTCALL = 25;
  public int JJTARGS = 26;
  public int JJTARGLIST = 27;


  public String[] jjtNodeName = {
    "program",
    "declarationList",
    "declaration",
    "varDeclaration",
    "funDeclaration",
    "params",
    "paramList",
    "param",
    "compoundStmt",
    "localDeclarations",
    "statementList",
    "statement",
    "expressionStmt",
    "selectionStmt",
    "iterationStmt",
    "returnStmt",
    "expression",
    "var",
    "simpleExperession",
    "relop",
    "additiveExpression",
    "term",
    "addop",
    "mulop",
    "factor",
    "call",
    "args",
    "argList",
  };
}
/* JavaCC - OriginalChecksum=1f9a283ec161a74b758cb759b7bc79e5 (do not edit this line) */
